---
vagrant_url_deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ architecture }}.deb"
vagrant_tmp_deb: "{{ tmp_dir }}/vagrant_{{vagrant_version}}.deb"
node_version_major: "12"
node_version: "{{ node_version_major }}.20.2-1nodesource1"
packages:
      - vim
      - ipcalc
      - tcpdump
      - dnsutils
      - make
      - curl
      - sudo
      - traceroute
      - strace
      - ack
      - nmap
      - net-tools
      - gcc
      - iptables
      - automake
      - autoconf
      - htop
      - git
      - ncdu
      - tmux
      - direnv
      - zsh
      - gpg
      - jq
      - pass
      - python3
      - python3-pip
      - iptables-persistent
      - virt-manager
      - ruby-full
      - libvirt-dev
      - rsync
      - libgtk-3-dev
      - most
      - tlp
      - fzf
      - scdaemon
      - pcscd
      - dirmngr
      - fping
      - youtube-dl
      - firmware-linux
      - bijiben
      - apparmor
      - apparmor-profiles
      - apparmor-utils
      - clamav
      - clamtk
      - rkhunter
      - chkrootkit
      - libpam-passwdqc
      - libpam-tmpdir
      - apt-listbugs
      - debsecan
      - debsums
      - needrestart
      - kubectl
      - openvpn
