---
- hosts: localhost
  remote_user: root

  vars_files:
    - vars/user.yml
    - vars/packages.yml
    - vars/system.yml

  roles:
    - system
    - user
    - packages
    - dotfiles
    - security
    - include_role:
      name: gnome
      when: gui == true
