---
- hosts: localhost
  remote_user: root

  vars_files:
    - vars/damyr.yml

  roles:
    - user
    - packages
    - dotfiles
    - security
    - include_role:
      name: gnome
      when: gui == true
