---
- hosts: localhost
  remote_user: root

  vars:
    user: damyr
    forward: true
    custom_hostname: laptop
    timezone: 'Europe/Paris'
    tmp_dir: "/tmp"
    vagrant_version: "2.2.7"
    architecture: "x86_64"

  roles:
    - user
    - packages
    - dotfiles
    - security
    - gnome
