---
- hosts: localhost
  remote_user: root

  vars:
    user: damyr
    forward: true
    custom_hostname: laptop
    timezone: 'Europe/Paris'

  roles:
    - user
    - packages
    - dotfiles
    - security
