---
- name: "ASDF set home var"
  set_fact:
    "asdf_user_home": "/home/{{ user }}"
  tags:
    - upgrade
    - asdf
- name: Install asdf plugins and versions
  block:
    - name: Add asdf plugins
      command: "asdf plugin add {{ item.name }}"
      register: plugin_add
      failed_when: 
        - plugin_add.rc != 0 
        - "'already added' not in plugin_add.stderr"
      changed_when: plugin_add.rc == 0
      with_items: "{{ asdf_plugins }}"

    - name: Install latest version for each plugin
      command: "asdf install {{ item.name }} latest"
      register: version_install
      failed_when:
        - version_install.rc != 0
        - "'is already installed' not in version_install.stderr"
      changed_when: version_install.rc == 0
      with_items: "{{ asdf_plugins }}"

    - name: Set global version for each plugin
      command: "asdf global {{ item.name }} latest"
      register: global_set
      changed_when: global_set.rc == 0
      with_items: "{{ asdf_plugins }}"

    - name: Reshim all plugins
      command: "asdf reshim"
      changed_when: false
  tags:
    - upgrade
    - asdf
