---
# https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
- name: "Install LSP ({{ item }})"
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - "yaml-language-server"
    - "pyright"
    - "@ansible/ansible-language-server"
    - "dockerfile-language-server-nodejs"
    - "bash-language-server"

- name: "Install LSP yaml"
  community.general.yarn:
    name: yaml-language-server
    global: yes
