---
- name: "Upgrade all packages to the latest version"
  become: "yes"
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "Install tools and stuff"
  become: "yes"
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes

- name: "Install AWS CLI"
  become: "yes"
  pip: >
   name=awscli
   state=latest

- name: "Install psutil"
  become: "yes"
  pip: >
   name=psutil
   state=latest

- name: "Install git precommit"
  become: "yes"
  pip: >
   name=pre-commit
   state=latest

- name: "Install detect secrets"
  tags: "detect-secrets"
  become: "yes"
  pip: >
   name=detect-secrets
   state=latest

- name: "Install tfenv"
  git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "/home/{{ user }}/.tfenv"
  become: "yes"
  become_user: "{{ user }}"

- name: "Check if Vagrant is already installed"
  command: dpkg-query -l vagrant
  register: deb_check

- name: "Download vagrant"
  get_url: url={{ vagrant_url_deb }} dest={{ vagrant_tmp_deb }}
  when: deb_check.stdout.find('no packages found') != -1

- name: "Install Vagrant"
  become: "yes"
  apt: deb={{ vagrant_tmp_deb }}
  when: deb_check.stdout.find('no packages found') != -1

- name: "Remove .deb file"
  file:
    path: "{{ vagrant_tmp_deb }}"
    state: absent
  when: deb_check.stdout.find('no packages found') != -1

- name: "Install nokogiri (for Vagrant)"
  become: "yes"
  gem:
    name: rake
    state: latest
