---
# GCP repo
- name: "Add Google gcloud (gcp) repository key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg" 
    state: present
  become: true

- name: "Add Google gcloud (gcp) repository"
  apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: true

# Spotify repo
- name: "Add Spotify repository key"
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg" 
    state: present
  become: true

- name: "Add Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true

# Hashicorp
- name: "Add Hashicorp repository key"
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg" 
    state: present
  become: true

- name: "Add Hashicorp repository"
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ stable_debian_codename }} main"
    state: present
  become: true

# NodeJS repo
- name: "Add NodeJS repository key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" 
    state: present
  become: true

- name: "Add NodeJS repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_version_major }}.x {{ stable_debian_codename }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_version_major }}.x {{ stable_debian_codename }} main"
  become: true

- name: "Upgrade all packages to the latest version"
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: yes
  tags: upgrade

- name: "Install tools and stuff"
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes
    force: yes
  tags: upgrade

- name: "Install Scaleway cli"
  become: true
  get_url:
    url: "https://github.com/scaleway/scaleway-cli/releases/download/v{{ scw_version }}/scaleway-cli_{{ scw_version }}_linux_amd64"
    dest: "/usr/local/bin/scw"
    mode: '0755'
  tags: upgrade

- name: "Install Starship cli"
  become: true
  unarchive:
    remote_src: yes
    src: "https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/usr/local/bin/"
    mode: '0755'
  tags: upgrade

- name: "install Packer (Nvim)"
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "/home/{{ user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  become: True
  become_user: "{{ user }}"
  tags: upgrade

- name: Install Packer stack
  include_tasks: vagrant.yml
  tags: upgrade

- name: Install pip packages
  include_tasks: pip.yml
  tags: upgrade

- name: Install asdf suff 
  include_tasks: asdf.yml

- name: Install Firefox
  include_tasks: firefox.yml
  tags: firefox

- name: Install LSP
  include_tasks: lsp.yml
  tags: upgrade
