---
# GCP repo
- name: "Add Google gcloud (gcp) repository key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg" 
    state: present
  become: "yes"

- name: "Add Google gcloud (gcp) repository"
  apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  become: "yes"

# Spotify repo
- name: "Add Spotify repository key"
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg" 
    state: present
  become: "yes"

- name: "Add Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: "yes"

# Hashicorp
- name: "Add Hashicorp repository key"
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg" 
    state: present
  become: "yes"

- name: "Add Hashicorp repository"
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ stable_debian_codename }} main"
    state: present
  become: "yes"

# NodeJS repo
- name: "Add NodeJS repository key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" 
    state: present
  become: "yes"

- name: "Add NodeJS repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_version_major }}.x {{ stable_debian_codename }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_version_major }}.x {{ stable_debian_codename }} main"
  become: "yes"

- name: "Upgrade all packages to the latest version"
  become: "yes"
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "Install tools and stuff"
  become: "yes"
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes
    force: yes

- name: "Install Scaleway cli"
  become: "yes"
  get_url:
    url: "https://github.com/scaleway/scaleway-cli/releases/download/v{{ scw_version }}/scw-{{ scw_version }}-linux-x86_64"
    dest: "/usr/local/bin/scw"
    mode: '0755'

- name: Install Packer stack
  include_tasks: vagrant.yml

- name: Install pip packages
  include_tasks: pip.yml

- name: Install asdf suff 
  include_tasks: asdf.yml
