---
- name: "Install pip package"
  become: "yes"
  pip: >
   name="{{ item.name }}"
   state="{{ item.version }}"
  loop:
    - { name: 'awscli', version: 'latest' }
    - { name: 'psutil', version: 'latest' }
    - { name: 'pre-commit', version: 'latest' }
    - { name: 'detect-secrets', version: 'latest' }
  tags: upgrade
