---
- name: install iptables persistent
  environment:
     DEBIAN_FRONTEND: noninteractive
  apt: pkg=iptables-persistent state=present
  become: true

- name: Copy iptables template rules over to /etc/iptables
  template: src=iptables.j2 dest=/etc/iptables/rules.v4
  notify: restart netfilter-persistent 
  become: true
