---
- name: Firewall rule - allow all loopback traffic
  become: 'yes'
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Firewall rule - allow established connections
  become: 'yes'
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT


- name: Firewall rule - drop any traffic without rule
  become: 'yes'
  iptables:
    chain: INPUT
    jump: DROP
