---
- name: Firewall setup
  include_tasks: firewall.yml

- name: rkhunter setup
  include_tasks: rkhunter.yml

- name: sysctl network hardening
  include_tasks: sysctl.yml

- name: files permissions hardening
  include_tasks: file_perm.yml

- name: PAM hardening
  include_tasks: pam.yml

- name: Add log on profil by default
  include_tasks: profil.yml
