---
- name: Add configuration files
  become: 'yes'
  copy:
    src: config/{{item}}
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    ['.zshrc','.vimrc', '.tmux.conf', '.gitconfig']

- name: Vim plug 
  become: 'yes'
  file:
    path: "/home/{{ user }}/.vim/autoload"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Download vim module Plug
  become: 'yes'
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user }}/.vim/autoload/plug.vim"
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ user }}"
