---
- name: "Add configuration files"
  become: 'yes'
  copy:
    src: ../files/{{item}}
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    ['.zshrc','.vimrc', '.tmux.conf']

- name: "Configure Gitfile"
  template: src=gitconig.j2 dest="/home/{{ user }}/.gitconfig"
  become: true
  become_user: "{{ user }}"

- name: "Vim plug"
  become: 'yes'
  file:
    path: "/home/{{ user }}/.vim/autoload"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Download vim module Plug"
  become: 'yes'
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user }}/.vim/autoload/plug.vim"
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Install vim plugins"
  shell: "vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty"
