---
- name: "Add configuration files"
  become: 'yes'
  copy:
    src: ../files/{{item}}
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    ['.zshrc','.vimrc', '.tmux.conf']
  tags: dotfiles

- name: "Configure Gitfile"
  template: src=gitconfig.j2 dest="/home/{{ user }}/.gitconfig"
  become: true
  become_user: "{{ user }}"
  tags: dotfiles

- name: "Vim plug"
  become: 'yes'
  file:
    path: "/home/{{ user }}/.vim/autoload"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: dotfiles

- name: "Download vim module Plug"
  become: 'yes'
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user }}/.vim/autoload/plug.vim"
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Install vim plugins"
  shell: "vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty"

- name: "Install vim coc plugin"
  shell: "vim +'CocInstall coc-pyright coc-json coc-yaml' +qall &> /dev/null < /dev/tty"

# Neovim
- name: "Init Neovim repo"
  become: 'yes'
  file:
    path: "/home/{{ user }}/.config/nvim/"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: dotfiles

- name: "Add configuration file for Neovim"
  become: 'yes'
  copy:
    src: ../files/init.lua
    dest: "/home/{{ user }}/.config/nvim/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: dotfiles

- name: "Add configuration for Starship prompt"
  become: 'yes'
  copy:
    src: ../files/starship.toml
    dest: "/home/{{ user }}/.config/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: dotfiles
