---
- name: "Create symlink for zsh"
  become: 'yes'
  file: 
    src: "/home/{{ user }}/.zshrc"
    dest: "/home/{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: link
  loop: "{{ alt_env }}"

- name: "Create symlink for vim"
  become: 'yes'
  file: 
    src: "/home/{{ user }}/.vimrc"
    dest: "/home/{{ item }}/.vimrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: link
  loop: "{{ alt_env }}"

- name: "Create symlink for Tmux"
  become: 'yes'
  file: 
    src: "/home/{{ user }}/.tmux.conf"
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: link
  loop: "{{ alt_env }}"
