---
# Create tfenv for local user
- name: "Deploy tfenv"
  become: 'yes'
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "/home/{{ item }}/.tfenv/"
  loop: "{{ alt_env }}"

- name: "Fix perm"
  become: 'yes'
  ansible.builtin.file:
    path: "/home/{{ item }}/.tfenv/"
    recurse: yes
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ alt_env }}"
