---
- name: "Update Hostname"
  hostname:
    name: "{{ custom_hostname }}"
  become: true

- name: "Set timezone"
  timezone:
    name: "{{ timezone }}"
  become: true

- name: "DNS setup"
  include_tasks: dns.yml
