- name: Ensure fonts directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ user }}/.fonts"
    - "/home/{{ user }}/.local/share/fonts"
  become: true

- name: Check if Nerd font Hack is present
  shell: "ls /home/{{ user }}/.local/share/fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: true
  become: true

- name: Download Nerd font Hack
  when: hack_exists is failed
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
    dest: "/home/{{ user }}/.local/share/fonts/"
    remote_src: true
  become: true

- name: Check if Nerd font symbols is present
  shell: "ls /home/{{ user }}/.local/share/fonts/*NerdFonts*"
  register: nerdfonts_exists
  ignore_errors: true
  become: true

- name: Download Nerd font
  when: nerdfonts_exists is failed
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/NerdFontsSymbolsOnly.zip
    dest: "/home/{{ user }}/.local/share/fonts/"
    remote_src: true
  become: true

- name: Check if jetbrains font is present
  shell: "ls /home/{{ user }}/.local/share/fonts/*JetBrainsMono*"
  register: jetbrains_exists
  ignore_errors: true
  become: true

- name: Download jetbrains font
  when: jetbrains_exists is failed
  unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "/home/{{ user }}/.local/share/fonts/"
    remote_src: true
  become: true
