---
- name: "Install tools and stuff"
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes

- name: "Remove tools (not needed, games etc.)"
  become: true
  apt:
    name: "{{ to_remove }}"
    state: absent

- name: "Copy wallpaper file"
  become: true
  become_user: "{{ user }}"
  copy:
    src: "files/wallpaper.jpg" 
    dest: "/home/{{ user }}/.wallpaper.jpg"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Parameter PC by using dconf
  include_tasks: dconf.yml

- name: Install fonts
  include_tasks: fonts.yml

- name: "Download icons (Paper)"
  get_url:
    url: "{{ url_deb_icons }}"
    dest: "{{ tmp_dir }}/paper_icon.deb"

- name: "Install icons (Paper)"
  become: true
  apt:
    deb: "{{ tmp_dir }}/paper_icon.deb"

- name: "Remove package archive"
  become: true
  file:
    path: "{{ tmp_dir }}/paper_icon.deb"
    state: absent

- name: "Gnome set icons"
  become: true
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Paper'"
    state: present

- name: "Ensure the Github projects directory exists"
  ansible.builtin.file:
    path: "~/Projets/Github"
    state: directory
    mode: '0755'

- name: "Clone the Marble-shell-theme repository"
  ansible.builtin.git:
    repo: 'https://github.com/imarkoff/Marble-shell-theme.git'
    dest: "~/Projets/Github/Marble-shell-theme"
    version: main

- name: "Run the install script"
  ansible.builtin.command:
    cmd: python ~/Projets/Github/Marble-shell-theme/install.py -a --filled

- name: "Set Gnome theme"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Marble-blue-light'"
    state: present
