---
- name: Parameter PC by using dconf
  include_tasks: dconf.yml

- name: "Install tools and stuff"
  become: "yes"
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes

- name: "Remove tools (not needed, games etc.)"
  become: "yes"
  apt:
    name: "{{ to_remove }}"
    state: absent

- name: "Copy wallpaper file"
  become: "yes"
  become_user: "{{ user }}"
  copy:
    src: "files/wallpaper.jpg" 
    dest: "/home/{{ user }}/.wallpaper.jpg"
    owner: "{{ user }}"
    group: "{{ user }}"


- name: "Download icons (Paper)"
  get_url:
    url: "{{ url_deb_icons }}"
    dest: "{{ tmp_dir }}/paper_icon.deb"

- name: "Install icons (Paper)"
  become: "yes"
  apt:
    deb: "{{ tmp_dir }}/paper_icon.deb"

- name: "Remove package archive"
  become: "yes"
  file:
    path: "{{ tmp_dir }}/paper_icon.deb"
    state: absent

- name: "Gnome set icons"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Paper'"
    state: present
