---
- name: "Install Gnome3"
  become: "yes"
  apt:
    pkg:
      - gnome
    state: present

- name: "Copy wallpaper file"
  become: "yes"
  become_user: "{{ user }}"
  copy:
    src: "files/wallpaper.png" 
    dest: "/home/{{ user }}/.wallpaper.png"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Set GNOME Wallpaper"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ user }}/.wallpaper.png'"

- name: "Gnome set theme"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Arc-Dark'"
    state: present

- name: "Gnome show date"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
    state: present

- name: "Gnome show battery percentage"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present

- name: "Gnome show seconds"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"
    state: present

- name: "Gnome set GTK theme"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc-Darker'"
    state: present

- name: "Gnome set WM theme"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/wm/preferences/theme"
    value: "'Arc-Darker'"
    state: present

- name: "Download icons (Paper)"
  get_url:
    url: "{{ url_deb_icons }}"
    dest: "{{ tmp_dir }}/paper_icon.deb"

- name: "Install icons (Paper)"
  become: "yes"
  apt:
    deb: "{{ tmp_dir }}/paper_icon.deb"

- name: "Remove package archive"
  become: "yes"
  file:
    path: "{{ tmp_dir }}/paper_icon.deb"
    state: absent

- name: "Gnome set icons"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Paper'"
    state: present

- name: "Set prefered apps"
  become: "yes"
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox-esr.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop']"
    state: present
